name: hub-config
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches: ['main']
    paths: ['hub-config/**', '!**README**']
  pull_request:
    branches: ['main']
    paths: ['hub-config/**', '!**README**']
  workflow_dispatch:
jobs:
  validate-hub-config:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
      - name: Update R
        run: |
          sudo apt-get update
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: Infectious-Disease-Modeling-Hubs/hubAdmin, any::sessioninfo
      - name: Run validations
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          library("hubAdmin")
          hubAdmin::validate_config(
            hub_path='.',
            config=c("admin"),
            config_path=NULL,
            schema_version="from_config",
            branch="main"
          )
          hubAdmin::validate_config(
            hub_path='.',
            config=c("tasks"),
            config_path=NULL,
            schema_version="from_config",
            branch="main"
          )
        shell: Rscript {0}
