name: model-output-pull
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  # push:
  #  branches: ['main']
  #  paths: ['model-output/**']
  pull_request:
    branches: ['main']
    paths: ['model-output/**', '!**README**']
  workflow_dispatch:
jobs:
  validate-submission:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
      - name: Update R
        run: |
          sudo apt-get update
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: Infectious-Disease-Modeling-Hubs/hubValidations, any::sessioninfo
      - name: Run validations
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          library("hubValidations")
          v <- hubValidations::validate_pr(
              gh_repo = Sys.getenv("GITHUB_REPOSITORY"),
              pr_number = Sys.getenv("PR_NUMBER"),
              skip_submit_window_check = FALSE
          )
          hubValidations::check_for_errors(v, verbose = TRUE)
        shell: Rscript {0}
